### ISSUE TITLE
Метод createQuiz(numberOfQuestions, quizName)

### ISSUE THREAD

**Issue by Fr0z3Nn** [Fr0z3Nn/it-quiz#31]
createQuiz(numberOfQuestions, quizName) выкидывает эксепшен при ситуации, когда в бд вопросов нет ни одного вопроса. Исправить.
Как вариант - отлавливать эксепшен в хэндлере глобальном (уже реализовано)
Обработать возврат в кастомном репозитории
![image](https://user-images.githubusercontent.com/60842252/114303673-03a9b880-9ad8-11eb-85c9-77e8318931c4.png)

**Comment by Fr0z3Nn** [comment]
Связано с корявым рандомом

**Comment by Fr0z3Nn** [comment]
ещё как вариант можно сначала вытаскивать лист айдишников

**Comment by Roberto-net** [comment]
я думаю, что надо вытащить лист и после этого уже создавать, но когда 0 вопросов в бд то он все равно же должен бросать исключение

**Comment by Roberto-net** [comment]
или по крайней мере писать что в бд нет готовых(существующих) вопросов

**Comment by Fr0z3Nn** [comment]
> или по крайней мере писать что в бд нет готовых(существующих) вопросов

нутк должен) А из-за критерии сейчас просто вылетает эксепшен без ответа, его можно в глоьал хэндлер запихнуть и обработать с выводом нормально сообщения
